# Generated by Django 6.0.3 on 2026-03-13 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSearchPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='назва')),
                ('language', models.CharField(choices=[('en', 'English'), ('fi', 'Suomi'), ('uk', 'Українська')], default='en', max_length=5, verbose_name='мова завдання')),
                ('is_public', models.BooleanField(default=False, verbose_name='публічний')),
                ('grid_size', models.PositiveSmallIntegerField(default=15, verbose_name='розмір сітки')),
                ('grid_data', models.JSONField(blank=True, default=dict, verbose_name='дані сітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'філворд',
                'verbose_name_plural': 'філворди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordSearchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='слово')),
                ('hint', models.CharField(blank=True, max_length=200, verbose_name='підказка')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='wordSearch.wordsearchpuzzle')),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'слова',
            },
        ),
        migrations.CreateModel(
            name='UserPuzzleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_words', models.JSONField(default=list, verbose_name='знайдені слова')),
                ('is_done', models.BooleanField(default=False, verbose_name='позначено як виконане')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_progress', to=settings.AUTH_USER_MODEL)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='wordSearch.wordsearchpuzzle')),
            ],
            options={
                'verbose_name': 'прогрес',
                'verbose_name_plural': 'прогрес користувачів',
                'unique_together': {('user', 'puzzle')},
            },
        ),
    ]
