# Generated by Django 6.0.3 on 2026-03-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearchpuzzle',
            name='category',
            field=models.CharField(
                choices=[('wordsearch', 'Філворд')],
                default='wordsearch',
                max_length=20,
                verbose_name='категорія',
            ),
        ),
    ]