# Generated by Django 6.0.3 on 2026-03-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordSearch', '0002_wordsearchpuzzle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpuzzleprogress',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='виконано'),
        ),
        migrations.AlterField(
            model_name='wordsearchpuzzle',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Suomi'), ('uk', 'Українська')], default='en', max_length=5, verbose_name='мова'),
        ),
    ]
